Expanded the flpz program to only run the piezo electric tensor if specified

diff --git a/flpz_input/b-script-flpzPert b/flpz_input/b-script-flpzPert
--- a/flpz_input/b-script-flpzPert
+++ b/flpz_input/b-script-flpzPert
@@ -14,6 +14,23 @@ if [ "$#" -ne 3 ]; then
     exit 1
 fi
 
+OPTSTRING=":p:"
+
+run_piezo="false"
+# Parse command line options
+while getopts "${OPTSTRING}" opt; do
+    case $opt in
+    p)
+        run_piezo=true
+        ;;
+    \?)
+        echo "Invalid option: -$OPTARG" >&2
+        exit 1
+        ;;
+    esac
+done
+shift $((OPTIND - 1))
+
 echo "Beginning FLPZ Program"
 
 # Read input files and calculate constant quantities
@@ -184,7 +201,11 @@ echo "Calculation of datapoints begins"
 # Calculate datapoints
 mkdir datapointInputFiles
 for eigVec in $eigVec_lines; do
-    bash datapointCalcofPert.sh "${input_file}_vec${eigVec}" 
+    if [ "$run_piezo" = "true" ]; then 
+        bash datapointCalcofPert.sh -p "${input_file}_vec${eigVec}" 
+    else
+        bash datapointCalcofPert.sh "${input_file}_vec${eigVec}"
+    fi
     mv "${input_file}_vec${eigVec}" datapointInputFiles
 done
 
